export const projects = [
    {
      title: 'E-commerce Store',
      description: "This is a React User Interface E-commerce Store made with React, React Router, and Styled Components. The project is in a progress. Plans: Implement Redux for a state management.",
        image: '/images/cruella.png',
        tags: ['React', 'React Router', 'Styled Components'],
      source: 'https://google.com',
      visit: 'https://google.com',
      id: 0,
    },
    {
      title: 'Beauty Salon',
      description:"This is a React User Interface Beauty Salon made with React, React Router, and Styled Components. The project has send message form validation that interacts with EmailJS. It's responsive. ",
      image: '/images/eden.png',
      tags: ['React', 'React Router', 'Styled Components'],
      source: 'https://google.com',
      visit: 'https://google.com',
      id: 1,
    },
    {
      title: 'Movies App',
      description: "This is a Movies App made with React and Redux Toolkit. It fetches the movies from OMDB API. The projects features asynchronous callbacks to the API and an advanced state management. It's responsive.  ",
        image: '/images/eden.png',
        tags: ['React', 'Redux', 'SCSS'],
      source: 'https://google.com',
      visit: 'https://google.com',
      id: 2,
    },
    {
      title: 'The Lion King',
      description: "This is the Lion King website made with HTML, CSS, Bootstrap, and JavaScript. It has basic SEO metatags, open graph concept, fancy CSS transitions and Google Fonts. It's responsive.  ",
      image: '/images/lion.png',
      tags: ['HTML5', 'CSS3', 'JavaScript'],
      source: 'https://google.com',
      visit: 'https://google.com',
      id: 3,
    },
    {
      title: 'Todo List App',
      description: "This is a todo list app made with React Hooks. There is no advanced state management here. The app allows to add a task, edit a task, post a task, and delete a task. It's responsive.  ",
        image: '/images/todo.png',
        tags: ['React'],
      source: 'https://google.com',
      visit: 'https://google.com',
      id: 2,
    },
    {
      title: 'The Music Player',
      description: "This is a simple music player with no advanced state management. It allows the user to play the song, skip the song, come back to the previous song. It's responsive. ",
      image: '/images/music.png',
      tags: ['React'],
      source: 'https://google.com',
      visit: 'https://google.com',
      id: 3,
    },
  ];
  
  export const TimeLineData = [
    { year: 2018, text: 'Started to learn programming', },
    { year: 2019, text: 'Started to freelancing', },
    { year: 2020, text: 'Divining deeper into technology world', },
    { year: 2021, text: 'Decided to join a company', },
    { year: 2022, text: 'Searching for a job at the company or a startup', },
  ];